# Generated by Django 5.0 on 2024-05-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0003_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='ad',
            field=models.TextField(max_length=300),
        ),
    ]
