# Generated by Django 5.0 on 2024-05-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0004_alter_adres_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefon',
            name='ad',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
