# Generated by Django 5.1.5 on 2025-02-13 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0005_alter_telefon_ad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, unique=True)),
                ('calisanlar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sirket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
