# Generated by Django 5.1.5 on 2025-02-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0006_sirket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sirket',
        ),
    ]
