# Generated by Django 5.0 on 2024-05-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hizmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, unique=True)),
                ('tanım', models.TextField(blank=True, null=True)),
                ('başlık', models.CharField(blank=True, max_length=300)),
                ('özet', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
