# Generated by Django 5.0 on 2024-05-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hizmet',
            old_name='başlık',
            new_name='baslik',
        ),
        migrations.RenameField(
            model_name='hizmet',
            old_name='özet',
            new_name='ozet',
        ),
        migrations.RenameField(
            model_name='hizmet',
            old_name='tanım',
            new_name='tanim',
        ),
    ]
