# Generated by Django 5.0 on 2024-05-05 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet', '0002_rename_başlık_hizmet_baslik_rename_özet_hizmet_ozet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hizmet',
            name='ozet',
            field=models.TextField(blank=True, default='Özet', null=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
