# Generated by Django 5.0 on 2024-05-05 15:51

import hizmet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet', '0003_alter_hizmet_ozet'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmet',
            name='image',
            field=models.ImageField(default='hizmetler/services.jpg', upload_to=hizmet.models.service_directory_path),
        ),
    ]
