# Generated by Django 5.0 on 2024-05-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet', '0005_açıklama'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Açıklama',
            new_name='HizmetAçıklama',
        ),
    ]
