# Generated by Django 5.0 on 2024-05-17 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmet', '0006_rename_açıklama_hizmetaçıklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hizmet',
            name='ozet',
            field=models.TextField(blank=True, default='Özet', null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
