# Generated by Django 5.0 on 2024-05-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gönderen', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=11)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('konu', models.CharField(max_length=100)),
                ('mesaj', models.TextField()),
            ],
        ),
    ]
