# Generated by Django 5.0 on 2024-05-01 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hizmet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(default='Proje Adı', max_length=200, unique=True)),
                ('açıklama', models.TextField(blank=True, null=True)),
                ('başlık', models.CharField(max_length=300, null=True, unique=True)),
                ('özet', models.CharField(max_length=1000, null=True, unique=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hizmet.hizmet')),
            ],
        ),
        migrations.CreateModel(
            name='ProjeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proje.proje')),
            ],
        ),
    ]
