# Generated by Django 5.0 on 2024-05-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proje',
            old_name='açıklama',
            new_name='aciklama',
        ),
        migrations.RenameField(
            model_name='proje',
            old_name='başlık',
            new_name='baslik',
        ),
        migrations.RenameField(
            model_name='proje',
            old_name='özet',
            new_name='ozet',
        ),
    ]
