# Generated by Django 5.0 on 2024-05-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0004_proje_eklenme_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='degisiklik_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
