# Generated by Django 5.0 on 2024-05-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0005_proje_degisiklik_tarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proje',
            name='degisiklik_tarihi',
        ),
        migrations.AlterField(
            model_name='proje',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
