# Generated by Django 5.0 on 2024-05-05 17:25

import proje.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0006_remove_proje_degisiklik_tarihi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeimage',
            name='camp',
        ),
        migrations.AddField(
            model_name='proje',
            name='resimler',
            field=models.ManyToManyField(blank=True, related_name='projeler', to='proje.projeimage'),
        ),
        migrations.AddField(
            model_name='projeimage',
            name='image',
            field=models.ImageField(default='projects/template.jpg', upload_to=proje.models.proje_directory_path),
        ),
    ]
