# Generated by Django 5.0 on 2024-05-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0007_remove_projeimage_camp_proje_resimler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proje',
            name='resimler',
        ),
        migrations.AddField(
            model_name='projeimage',
            name='proje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='proje.proje'),
        ),
    ]
