# Generated by Django 5.0 on 2024-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0008_remove_proje_resimler_projeimage_proje'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeimage',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
