# Generated by Django 5.0 on 2024-05-05 18:00

import proje.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0009_projeimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='kapak_resmi',
            field=models.ImageField(default='projects/template.jpg', upload_to=proje.models.proje_directory_path),
        ),
        migrations.AlterField(
            model_name='projeimage',
            name='image',
            field=models.ImageField(null=True, upload_to=proje.models.proje_directory_path),
        ),
    ]
