# Generated by Django 5.0 on 2024-05-05 18:03

import proje.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0011_alter_proje_kapak_resmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='kapak_resmi',
            field=models.ImageField(default='projects/template.jpg', upload_to=proje.models.proje_directory_path),
        ),
    ]
