# Generated by Django 5.0 on 2024-05-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0012_alter_proje_kapak_resmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeimage',
            name='order',
        ),
    ]
