# Generated by Django 5.0 on 2024-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0013_remove_projeimage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjeAçıklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanim', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
