# Generated by Django 5.0 on 2024-05-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0014_projeaçıklama'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjeImage',
            new_name='ProjeResim',
        ),
    ]
