# Generated by Django 5.0 on 2024-05-22 10:02

import proje.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0015_rename_projeimage_projeresim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='kapak_resmi',
            field=models.ImageField(blank=True, default='projects/template.jpg', null=True, upload_to=proje.models.proje_directory_path),
        ),
    ]
