# Generated by Django 5.0 on 2024-05-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0017_alter_proje_ad_alter_proje_id_alter_proje_ozet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeresim',
            name='rotate_button',
            field=models.BooleanField(default=False),
        ),
    ]
