# Generated by Django 5.0 on 2024-05-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0018_projeresim_rotate_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeresim',
            name='rotate_button',
        ),
    ]
