# Generated by Django 5.0 on 2024-05-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0019_remove_projeresim_rotate_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='eklenme_tarihi',
            field=models.DateTimeField(),
        ),
    ]
