# Generated by Django 5.0 on 2024-05-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0020_alter_proje_eklenme_tarihi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proje',
            old_name='eklenme_tarihi',
            new_name='proje_tarihi',
        ),
    ]
