# Generated by Django 5.0 on 2024-05-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0021_rename_eklenme_tarihi_proje_proje_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
