# Generated by Django 5.0 on 2024-06-06 14:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0023_alter_proje_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proje',
            name='ozet',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
    ]
