# Generated by Django 5.0 on 2024-06-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0024_alter_proje_aciklama_alter_proje_ozet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='proje_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
