# Generated by Django 5.0 on 2024-06-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0025_alter_proje_proje_tarihi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proje',
            options={'ordering': ['-order']},
        ),
    ]
