# Generated by Django 5.1.5 on 2025-01-27 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DosyaTürü',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('adet', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('dosya', models.FileField(upload_to='dosyalar/')),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('toplam_gereken_sayi', models.IntegerField(default=0)),
                ('dosya_turu_sıra', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to=settings.AUTH_USER_MODEL)),
                ('dosya_turu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosya.dosyatürü')),
            ],
            options={
                'ordering': ['-yuklenme_tarihi'],
            },
        ),
    ]
