# Generated by Django 5.1.5 on 2025-01-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosya', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosya',
            old_name='dosya_turu_sıra',
            new_name='dosya_turu_sira',
        ),
    ]
