# Generated by Django 5.1.5 on 2025-01-29 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosya', '0002_rename_dosya_turu_sıra_dosya_dosya_turu_sira'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosya',
            name='customer',
        ),
        migrations.AddField(
            model_name='dosya',
            name='musteri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosyalar', to=settings.AUTH_USER_MODEL),
        ),
    ]
