# Generated by Django 5.1.5 on 2025-01-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosya', '0003_remove_dosya_customer_dosya_musteri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosya',
            name='toplam_gereken_sayi',
        ),
    ]
