# Generated by Django 5.1.5 on 2025-02-02 18:08

import django.db.models.deletion
import dosya.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosya', '0004_remove_dosya_toplam_gereken_sayi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya',
            name='dosya',
            field=models.FileField(upload_to=dosya.models.dosya_yolu),
        ),
        migrations.AlterField(
            model_name='dosya',
            name='dosya_turu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dosya.dosyatürü'),
        ),
    ]
