# Generated by Django 5.1.5 on 2025-02-09 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosya', '0005_alter_dosya_dosya_alter_dosya_dosya_turu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya',
            name='yuklenme_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
