# Generated by Django 5.1.5 on 2025-02-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosya', '0006_alter_dosya_yuklenme_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosyatürü',
            name='sene',
            field=models.IntegerField(default=2024),
        ),
    ]
