# Generated by Django 5.1.5 on 2025-02-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosya', '0007_dosyatürü_sene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosyatürü',
            name='sene',
            field=models.IntegerField(default=2025),
        ),
    ]
