# Generated by Django 5.1.5 on 2025-02-13 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosya', '0009_remove_dosya_musteri_dosya_sirket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dosya',
            name='degisiklik_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dosya',
            name='degisiklik_yapan_kisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
