# Generated by Django 5.1.6 on 2025-02-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosya', '0011_remove_dosya_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya',
            name='dosya_turu_sira',
            field=models.IntegerField(default=1),
        ),
    ]
