# Generated by Django 5.1.5 on 2025-03-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosya', '0012_alter_dosya_dosya_turu_sira'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosya',
            options={'ordering': ['-yuklenme_tarihi'], 'verbose_name': 'Rapor', 'verbose_name_plural': 'Raporlar'},
        ),
        migrations.AlterModelOptions(
            name='dosyatürü',
            options={'verbose_name': 'Ölçüm Türü', 'verbose_name_plural': 'Ölçüm Türleri'},
        ),
        migrations.RenameField(
            model_name='dosya',
            old_name='dosya_turu',
            new_name='olcum_turu',
        ),
        migrations.RenameField(
            model_name='dosya',
            old_name='dosya_turu_sira',
            new_name='olcum_turu_sira',
        ),
    ]
