# Generated by Django 5.0 on 2024-05-01 17:55

import slayt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slayt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='slider/idle.jpg', upload_to=slayt.models.slider_directory_path)),
            ],
        ),
    ]
