# Generated by Django 5.0 on 2024-05-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slayt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slayt',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
