# Generated by Django 5.0 on 2024-05-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slayt', '0003_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaytAçıklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanim', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
