# Generated by Django 5.0 on 2024-05-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BizKimiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanim', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Madde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Misyonumuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanim', models.CharField(max_length=200, unique=True)),
                ('madde', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kurumsal.madde')),
            ],
        ),
        migrations.CreateModel(
            name='Vizyonumuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanim', models.CharField(max_length=200, unique=True)),
                ('madde', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kurumsal.madde')),
            ],
        ),
    ]
