# Generated by Django 5.0 on 2024-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizkimiz',
            name='tanim',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
