# Generated by Django 5.0 on 2024-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0002_alter_bizkimiz_tanim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misyonumuz',
            name='tanim',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='vizyonumuz',
            name='tanim',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
