# Generated by Django 5.0 on 2024-05-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0003_alter_misyonumuz_tanim_alter_vizyonumuz_tanim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizkimiz',
            name='tanim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misyonumuz',
            name='tanim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vizyonumuz',
            name='tanim',
            field=models.TextField(blank=True, null=True),
        ),
    ]
