# Generated by Django 5.0 on 2024-05-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0004_alter_bizkimiz_tanim_alter_misyonumuz_tanim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misyonumuz',
            name='madde',
        ),
        migrations.RemoveField(
            model_name='vizyonumuz',
            name='madde',
        ),
        migrations.AddField(
            model_name='misyonumuz',
            name='madde',
            field=models.ManyToManyField(blank=True, to='kurumsal.madde'),
        ),
        migrations.AddField(
            model_name='vizyonumuz',
            name='madde',
            field=models.ManyToManyField(blank=True, to='kurumsal.madde'),
        ),
    ]
