# Generated by Django 5.0 on 2024-05-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0005_remove_misyonumuz_madde_remove_vizyonumuz_madde_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belgeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='madde',
            name='aciklama',
            field=models.CharField(default='Açıklama', max_length=200, unique=True),
        ),
    ]
