# Generated by Django 5.0 on 2024-05-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0006_belgeler_madde_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madde',
            name='aciklama',
            field=models.CharField(default='Açıklama', max_length=200, null=True, unique=True),
        ),
    ]
