# Generated by Django 5.0 on 2024-05-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0010_remove_madde_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='madde',
            name='aciklama',
            field=models.CharField(default='Açıklama', max_length=200),
        ),
    ]
