# Generated by Django 5.0 on 2024-05-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0012_belgeler_belge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Belgeler',
            new_name='Belge',
        ),
    ]
