# Generated by Django 5.0 on 2024-05-05 14:33

import kurumsal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0013_rename_belgeler_belge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belge',
            name='belge',
            field=models.FileField(default='documents/isguvenligi.pdf', upload_to=kurumsal.models.document_directory_path),
        ),
    ]
