# Generated by Django 5.0 on 2024-05-05 15:49

import kurumsal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0014_alter_belge_belge'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizkimiz',
            name='image',
            field=models.ImageField(default='hakkimizda/about.jpg', upload_to=kurumsal.models.about_directory_path),
        ),
        migrations.AddField(
            model_name='misyonumuz',
            name='image',
            field=models.ImageField(default='misyonumuz/mission.jpg', upload_to=kurumsal.models.misyonumuz_directory_path),
        ),
        migrations.AddField(
            model_name='vizyonumuz',
            name='image',
            field=models.ImageField(default='vizyonumuz/vision.jpg', upload_to=kurumsal.models.vizyonumuz_directory_path),
        ),
    ]
