# Generated by Django 5.0 on 2024-05-12 17:32

import kurumsal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0016_belge_kapak_resmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizkimiz',
            name='e_katalog',
            field=models.FileField(null=True, upload_to=kurumsal.models.document_directory_path),
        ),
    ]
