# Generated by Django 5.0 on 2024-05-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0018_sayac'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sayac',
            new_name='Sayaç',
        ),
    ]
