# Generated by Django 5.0 on 2024-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0019_rename_sayac_sayaç'),
    ]

    operations = [
        migrations.AddField(
            model_name='sayaç',
            name='name',
            field=models.CharField(default='Sayaç', max_length=20),
        ),
    ]
