# Generated by Django 5.0 on 2024-05-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0021_rename_çalışan_sayaç_calisan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sayaç',
        ),
    ]
