# Generated by Django 5.0 on 2024-05-18 13:06

import kurumsal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0022_delete_sayaç'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belge',
            name='belge',
            field=models.FileField(null=True, upload_to=kurumsal.models.document_directory_path),
        ),
    ]
