# Generated by Django 5.0 on 2024-05-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0023_alter_belge_belge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belge',
            name='ad',
            field=models.CharField(max_length=200),
        ),
    ]
