# Generated by Django 5.0 on 2024-06-06 14:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0024_alter_belge_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizkimiz',
            name='tanim',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misyonumuz',
            name='tanim',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vizyonumuz',
            name='tanim',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
