# Generated by Django 5.0 on 2024-06-06 14:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0025_alter_bizkimiz_tanim_alter_misyonumuz_tanim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madde',
            name='aciklama',
            field=ckeditor.fields.RichTextField(default='Açıklama', max_length=200),
        ),
    ]
