# Generated by Django 5.1.5 on 2025-03-02 17:49

import django.db.models.deletion
import kurumsal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0026_alter_madde_aciklama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belge',
            name='belge',
        ),
        migrations.AlterField(
            model_name='belge',
            name='kapak_resmi',
            field=models.ImageField(default='kapak/taban.jpeg', upload_to='cover_directory_path'),
        ),
        migrations.CreateModel(
            name='BelgeOge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(null=True, upload_to=kurumsal.models.document_directory_path)),
                ('pdf_resim', models.ImageField(blank=True, null=True, upload_to=kurumsal.models.document_image_directory_path)),
                ('belge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belgeler', to='kurumsal.belge')),
            ],
        ),
    ]
