# Generated by Django 5.1.5 on 2025-03-02 18:37

import kurumsal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0027_remove_belge_belge_alter_belge_kapak_resmi_belgeoge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belge',
            name='kapak_resmi',
            field=models.ImageField(default='kapak/taban.jpeg', upload_to=kurumsal.models.cover_directory_path),
        ),
    ]
