# Generated by Django 5.0 on 2024-05-12 13:38

import kariyer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kariyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KariyerGörsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanim', models.CharField(default='Kariyer Görseli', max_length=20, null=True)),
                ('image', models.ImageField(default='kariyer/about.jpg', upload_to=kariyer.models.mesaj_directory_path)),
            ],
        ),
    ]
