# Generated by Django 5.0 on 2024-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kariyer', '0002_kariyergörsel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kariyergörsel',
            name='tanim',
            field=models.CharField(default='Kariyer Görseli', max_length=50, null=True),
        ),
    ]
