# Generated by Django 5.0 on 2024-06-06 14:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kariyer', '0003_alter_kariyergörsel_tanim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kariyeraçıklama',
            name='tanim',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
