# Generated by Django 5.1.5 on 2025-02-13 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sirket',
            name='calisanlar',
        ),
        migrations.AddField(
            model_name='sirket',
            name='calisanlar',
            field=models.ManyToManyField(related_name='sirketler', to=settings.AUTH_USER_MODEL),
        ),
    ]
