# Generated by Django 5.1.5 on 2025-02-13 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirket', '0002_remove_sirket_calisanlar_sirket_calisanlar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sirket',
            name='calisanlar',
        ),
        migrations.AddField(
            model_name='sirket',
            name='calisanlar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sirket', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
