# Generated by Django 5.1.5 on 2025-02-13 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirket', '0003_remove_sirket_calisanlar_sirket_calisanlar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sirket',
            name='calisanlar',
        ),
        migrations.CreateModel(
            name='SirketCalisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sirket.sirket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sirket',
            name='calisanlar',
            field=models.ManyToManyField(related_name='sirket', through='sirket.SirketCalisan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sirketcalisan',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_in_sirket'),
        ),
    ]
