# Generated by Django 5.1.5 on 2025-02-13 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirket', '0004_remove_sirket_calisanlar_sirketcalisan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sirketcalisan',
            name='unique_user_in_sirket',
        ),
        migrations.RenameField(
            model_name='sirketcalisan',
            old_name='user',
            new_name='calisan',
        ),
        migrations.AddConstraint(
            model_name='sirketcalisan',
            constraint=models.UniqueConstraint(fields=('calisan',), name='unique_calisan_in_sirket'),
        ),
    ]
