# Generated by Django 5.1.5 on 2025-08-16 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirket', '0005_remove_sirketcalisan_unique_user_in_sirket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sirketcalisan',
            name='unique_calisan_in_sirket',
        ),
        migrations.AddConstraint(
            model_name='sirketcalisan',
            constraint=models.UniqueConstraint(fields=('sirket', 'calisan'), name='uniq_sirket_calisan'),
        ),
    ]
